Update quiz.html
Big-Climate/website-project pull request #54
Opened 2023-12-12 21:57 UTC by MaMaMadSheep

MERGE QUIZ

2023-12-12 21:59 UTC, QATomB reviewed
well done!

2023-12-13 14:16 UTC, QATomB approved these changes
looks all good! good stuff

2023-12-13 14:31 UTC, lonewonder0 requested changes
Please separate out your <style> tags into a .css file placing it in the folder /css
Should be a simple copy paste, then you just have to include, for example, 
`<link rel="stylesheet" href="./css/EcoWithYouQuestion.css" />`
Between your `<head>` tag.

Please do this for all three .html files I makes it easier for us to make quick changes to formatting and tidies up the .html so we know it's just html. Love me some convention.

Other than this minor formatting thing it's a really great job the quiz looks great Maddie!

2023-12-13 17:00 UTC, lonewonder0 approved these changes

2023-12-13 17:01 UTC, merged